### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by jinggoing** [ujnzxw/oh-my-earth#1]
when I install than enter oh-my-earth
it show me 
Traceback (most recent call last):
  File "/usr/local/bin/oh-my-earth", line 13, in <module>
    from PIL import Image
ImportError: No module named PIL

how to deal with it

**Comment by hellozjf** [comment]
I have the some question, I do it in Ubuntu16.04
```
zjf@zjf-ubuntu-pc:~/code/git/oh-my-earth$ oh-my-earth 
Traceback (most recent call last):
  File "/usr/local/bin/oh-my-earth", line 13, in <module>
    from PIL import Image
ImportError: No module named PIL
```

**Comment by hellozjf** [comment]
@jinggoing 
You need to install some python libraries`pip install image`
Then you will face some other questions, do following steps
```
sudo easy_install pytz
sudo easy_install tzlocal
sudo easy_install appdirs
```

It's easy to solve, believe me.

**Comment by jinggoing** [comment]
thx , your way is useful for me
