### ISSUE TITLE
There are too many processes runs on Ubuntu

### ISSUE THREAD

**Issue by chinadx** [ujnzxw/oh-my-earth#3]
## I've installed the amazing project. but I found there are many processes runs:

shaun@shaun-ThinkPad-T420:~/Workspace/hotel$ ps -ef|grep python
shaun     3486  3485  0 22:30 ?        00:00:14 python /usr/local/bin/oh-my-earth
shaun     3487  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3488  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3489  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3490  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3491  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3492  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3493  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3494  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3495  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3496  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3497  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3498  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3499  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3500  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3501  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3502  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3503  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3504  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3505  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3506  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3507  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3508  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3509  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3510  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3511  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3512  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3513  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3514  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3515  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3516  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3517  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun     3518  3486  0 22:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19651 19650  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19652 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19653 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19654 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19655 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19656 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19657 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19658 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19659 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19660 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19661 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19662 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19663 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19664 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19665 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19666 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19667 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19668 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19669 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19670 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19671 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19672 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19673 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19674 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19675 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19676 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19677 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19678 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19679 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19680 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19681 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19682 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
shaun    19683 19651  0 23:30 ?        00:00:00 python /usr/local/bin/oh-my-earth
## is this allright?

I'm using Ubuntu 16.04LTS, and set crontab like blow:
*/10 \* \* \* \* /usr/local/bin/oh-my-earth

**Comment by chinadx** [comment]
Hi, I'm back.
There are no more duplicated processes now after I set the "level = 4" in "config.py".
I guess it because the low net speed.

**Comment by ujnzxw** [comment]
download with multi-process:
the picture will divided into level*level parts and download every part with one single process.
